# Generated by Django 6.0.5 on 2026-05-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aéroport',
                'verbose_name_plural': 'Aéroports',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pays_rattachement', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Compagnie',
                'verbose_name_plural': 'Compagnies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='types_avions/')),
                ('longueur_piste_necessaire', models.PositiveIntegerField(help_text='Longueur de piste minimale en mètres')),
            ],
            options={
                'verbose_name': "Type d'avion",
                'verbose_name_plural': "Types d'avions",
                'ordering': ['marque', 'modele'],
            },
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('longueur', models.PositiveIntegerField(help_text='Longueur en mètres')),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes', to='gestion.aeroport')),
            ],
            options={
                'verbose_name': 'Piste',
                'verbose_name_plural': 'Pistes',
                'ordering': ['aeroport', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom ou immatriculation de l'avion", max_length=200)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avions', to='gestion.compagnie')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avions', to='gestion.typeavion')),
            ],
            options={
                'verbose_name': 'Avion',
                'verbose_name_plural': 'Avions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=200)),
                ('datetime_depart', models.DateTimeField()),
                ('datetime_arrivee', models.DateTimeField()),
                ('aeroport_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_arrivee', to='gestion.aeroport')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_depart', to='gestion.aeroport')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='gestion.avion')),
                ('piste_arrivee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vols', to='gestion.piste')),
            ],
            options={
                'verbose_name': 'Vol',
                'verbose_name_plural': 'Vols',
                'ordering': ['datetime_depart'],
            },
        ),
    ]
